import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useGetProductById } from "~/pages/hooks/useGetProductById";
import { api } from "~/utils/api";

const ProductView: NextPage = () => {
  const product = useGetProductById();
 
  console.log(product)

  return (
    <>
      <Head>
        <title>view product</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col ">
        <h1 className="text-4xl text-white m-4 ml-0">Items for sale</h1>
        <p className="container grid grid-cols-4 gap-12 text-2xl ">
         {product?.name}
         </p>
         <p>{product?.description}</p>
         <p>Rp.{product?.price}</p>
         
         <Link 
         href={`/features/chat/${product?.id}`}
          >
         <button className="bg-blue-400">
            chat
            </button>
            </Link>
        
      </main>
    </>
  );
};

export default ProductView;
