import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useGetProductById } from "~/pages/hooks/useGetProductById";
import { api } from "~/utils/api";

const Dasboard: NextPage = () => {
    const { data:products } = api.product.getAllProductById.useQuery()

  return (
    <>
      <Head>
        <title>view product</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" font-helvetica">
      <div className="flex h-screen">
      {/* Sidebar */}
      <aside className="bg-gray-800 w-1/5 py-8 px-4 text-white">
        <h1 className="text-2xl font-semibold">Product Dashboard</h1>
        <ul className="mt-6 space-y-3">
          <li className="px-2 py-1 rounded-md hover:bg-gray-700">Dashboard</li>
          <li className="px-2 py-1 rounded-md hover:bg-gray-700">Orders</li>
          <li className="px-2 py-1 rounded-md hover:bg-gray-700">Products</li>
          {/* Add more menu items */}
        </ul>
      </aside>

      {/* Main Content */}
      <main className="flex-1 bg-gray-100">
        {/* Add your dashboard components here */}
        <div className=" w-full h-10 text-xl font-bold p-4">All Product</div>

        <div className=" h-[90vh] w-full mt-4">
            <div className="flex flex-row justify-between p-4 text-xl border-black border-b-2 border-t-2">
                <div className="">product name</div>
                <div className="">id</div>
                <div className="">price</div>
                <div className="">active</div>
                <div className=""></div>
            </div>   

            <div className="bg-green-400 flex flex-row flex-wrap p-4">
                {products?.map((product) => {
                    return(
                      <>
                        <div className="bg-blue-200 ">{product.name}</div>
                      
                        <div className="bg-blue-200 ">{product.price}</div>
                        <div className="flex-row flex">
                        <button type="button" className="font-medium rounded-lg px-5 py-2.5 mr-2  bg-black text-white flex flex-row items-center  ">
                        <svg className="w-4 h-6 mr-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.414 2.586a2 2 0 00-2.828 0L7 10.172V13h2.828l7.586-7.586a2 2 0 000-2.828z"></path><path fill-rule="evenodd" d="M2 6a2 2 0 012-2h4a1 1 0 010 2H4v10h10v-4a1 1 0 112 0v4a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" clip-rule="evenodd"></path></svg>
                        edit item
                        </button>
                        <button type="button" className="font-medium rounded-lg px-5 py-2.5 mr-2  bg-black text-white flex flex-row items-center  ">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-4 h-6 mr-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                            </svg>
                            delete item
                        </button>
                        </div>
                      </>         
                    )
                })}
            </div> 
         </div>
      </main>
    </div>  
      </main>
    </>
  );
};

export default Dasboard;
