import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
// import { useGetProductById } from "~/pages/hooks/useGetProductById";
import { api } from "~/utils/api";
import EditProductModal from "./editProductModal";
import DeleteIcon from "~/pages/assets/deleteIcon";
import { useDeleteProduct } from "~/pages/hooks/useDeleteProduct";

const Dasboard: NextPage = () => {
  const { data: products, refetch } = api.product.getAllProductById.useQuery();
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedProduct, setSelectedProduct] = useState(products);
  const deleteProduct = useDeleteProduct();
  const [selectedProductId, setSelectedProductId] = useState<string | null>(
    null
  );

  const handleEditProduct = (products: any) => {
    setSelectedProduct(products);
    setIsModalOpen(true);
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
  };

  const handleClick = async () => {
    // console.log(id);
    try {
      await deleteProduct(selectedProductId);
      setIsToastOpen(false);
      refetch();
    } catch (error) {
      console.log(error);
    }
  };

  const handleOpenToast = (id: any) => {
    setSelectedProductId(id);
    setIsToastOpen(true);
  };

  const [isToastOpen, setIsToastOpen] = useState(false);

  const Toast = ({ productId }: any) => {
    console.log(productId);
    return (
      <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-50">
        <div className="rounded-lg bg-white p-4">
          <p className="mb-2 text-lg font-bold text-black">Are you sure?</p>
          <div className="flex justify-center space-x-4">
            <button
              onClick={() => handleClick()}
              className="rounded bg-blue-500 px-4 py-2 text-white hover:bg-blue-600"
            >
              Yes
            </button>
            <button
              onClick={() => setIsToastOpen(false)}
              className="rounded bg-gray-500 px-4 py-2 text-white hover:bg-gray-600"
            >
              No
            </button>
          </div>
        </div>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>view product</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-[#F8F8F8] font-helvetica">
        <div className="flex h-screen">
          {/* Sidebar */}
          <aside className="m-2 w-1/5 rounded-md bg-black px-4 py-8 text-white">
            <h1 className="text-2xl font-semibold">Product Dashboard</h1>
            <ul className="mt-6 space-y-3">
              <li className="rounded-md px-2 py-1 hover:bg-gray-700">
                Dashboard
              </li>
              <li className="rounded-md px-2 py-1 hover:bg-gray-700">Orders</li>
              <li className="rounded-md px-2 py-1 hover:bg-gray-700">
                Products
              </li>
              {/* Add more menu items */}
            </ul>
          </aside>

          {/* Main Content */}
          <main className="flex-1 bg-gray-100">
            {/* Add your dashboard components here */}
            <div className=" h-10 w-full p-4 text-xl font-bold">
              All Product
            </div>

            <div className=" mt-4 h-[90vh] w-full  pr-2">
              <div className="flex flex-row justify-between rounded-t-md border-b border-white bg-black p-2 text-xl text-white">
                <div className=" w-1/5">product name</div>
                <div className=" w-1/5">price</div>
                <div className=" w-1/5">stok</div>

                <div className=" w-1/5">active</div>
                <div className=" w-1/5"></div>
              </div>

              {isToastOpen && <Toast productId={selectedProductId} />}

              {products?.map((product) => {
                return (
                  <div className="flex flex-col">
                    <div className=" flex flex-row items-center justify-between border-b bg-black p-4  text-white ">
                      <>
                        {/* {isToastOpen && <Toast productId={product.id} />} */}
                        <div className=" flex w-1/5 flex-row truncate ">
                          <img
                            src={product.image[0]?.url}
                            className="mr-2 h-14 w-14 rounded-md"
                          ></img>
                          <div className="flex flex-col">
                            <p>{product.name} </p>
                            <p>SKU: - </p>
                          </div>
                        </div>
                        <div className=" w-1/5">{product.price}</div>
                        <div className=" w-1/5">1</div>

                        <div className=" w-1/5">
                          <label className="relative inline-flex cursor-pointer items-center">
                            <input
                              type="checkbox"
                              value=""
                              className="peer sr-only"
                            />
                            <div className="h-6 w-11 rounded-full bg-gray-200 after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:border after:border-gray-300 after:bg-white after:transition-all after:content-[''] peer-checked:after:translate-x-full peer-checked:after:border-white peer-focus:outline-none peer-focus:ring-4 dark:border-gray-600 dark:bg-gray-700 "></div>
                            <span className="ml-3 text-sm font-medium text-gray-900 dark:text-gray-300"></span>
                          </label>
                        </div>

                        <div className="flex w-1/5 flex-row justify-between">
                          <button
                            onClick={() => handleEditProduct(product)}
                            type="button"
                            className="mr-2 flex flex-row items-center rounded-lg bg-[#F8F8F8] px-5 py-2.5 font-medium text-black  "
                          >
                            edit item
                          </button>
                          <button
                            type="button"
                            className="mr-2 flex flex-row items-center rounded-lg  bg-[#F8F8F8] px-5 py-2.5 font-medium text-black"
                            // onClick={() => handleClick(product.id)}
                            onClick={() => handleOpenToast(product.id)}
                          >
                            <DeleteIcon />
                            delete item
                          </button>
                        </div>
                      </>
                    </div>
                  </div>
                );
              })}

              {isModalOpen && (
                <EditProductModal
                  onClose={handleCloseModal}
                  product={selectedProduct}
                  refetch={refetch}
                />
              )}
            </div>
          </main>
        </div>
      </main>
    </>
  );
};

export default Dasboard;
