import { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import ProductDetails from "~/components/product/ProductDetals";
import { useGetProductById } from "~/hooks/useGetProductById";

const ProductView: NextPage = () => {
  const { data, error } = useGetProductById();
  const [mainImage, setMainImage] = useState<string | undefined>(
    data?.image[0]?.url
  );

  useEffect(() => {
    if (data && data.image.length > 0) {
      setMainImage(data.image[0]?.url);
    }
  }, [data]);

  if (!data) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#E9E9E9]">
        Loading...
      </div>
    ); // Replace with your loading UI
  }

  const handleThumbnailClick = (thumbnailUrl: string) => {
    setMainImage(thumbnailUrl);
  };

  const {
    name,
    price,
    condition,
    location,
    description,
    author,
    authorId,
    image,
  } = data;

  return (
    <>
      <Head>
        <title>View Product</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen bg-[#E9E9E9] font-helvetica">
        <div className="container m-4 mx-auto sm:mt-10">
          <div className="flex flex-col justify-between md:gap-10 lg:flex-row lg:gap-16 ">
            {/* Main Image and Thumbnails */}

            <div className="flex flex-col gap-6 lg:w-2/4 ">
              <img
                src={mainImage || ""}
                alt=""
                className="aspect-square h-full w-full object-cover"
              />
              <div className="flex h-24 flex-row justify-center sm:items-end">
                {data?.image.map((thumbnail, index) => (
                  <img
                    key={index}
                    src={thumbnail.url}
                    alt=""
                    className="mr-3 h-14 w-14 cursor-pointer"
                    onClick={() => handleThumbnailClick(thumbnail.url)}
                  />
                ))}
              </div>
            </div>

            <ProductDetails
              name={name}
              price={price}
              condition={condition}
              location={location}
              description={description}
              authorId={authorId}
              author={author}
            />
          </div>
        </div>
      </main>
    </>
  );
};

export default ProductView;
