// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";

import { api } from "~/utils/api";

import Select from "react-select";
import { categoryOptions } from "../constants/categoryOptions";
import { sortOptions } from "../constants/sortOptions";
import ProductCard from "~/components/productCard";

export default function Home() {
  const products = api.product.getAll.useQuery();

  // console.log(products.data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar/> */}
      <main className="flex min-h-screen flex-col items-center bg-[#F8F8F8]">
        <div className="container  flex h-20 items-center justify-between bg-slate-50 ">
          <div className="ml-auto w-60">
            <Select
              options={sortOptions}
              placeholder="Sort by"
              styles={{
                control: (baseStyles, state) => ({
                  ...baseStyles,
                  border: "1px solid black",
                  boxShadow: "none",
                  "&:hover": {
                    border: "1px solid black",
                  },
                }),
              }}
              isSearchable
              maxMenuHeight={5 * 40}
            />
          </div>
        </div>

        <div className="bg-slate-40 container grid grid-cols-5 gap-8 text-2xl text-white">
          {products?.data?.map((product) => (
            <ProductCard key={product.id} product={product} />
          ))}
        </div>
      </main>
    </>
  );
}
