// import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";
import  Navbar  from "./components/Navbar";
import { api } from "~/utils/api";
import ProductCard from "./components/productCard";

export default function Home() {
  const products = api.product.getAll.useQuery()

  // console.log(products.data)
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Navbar/> */}
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#F8F8F8]">
      <div className="container grid grid-cols-4 gap-12 text-2xl text-white">
          {products?.data?.map((product) => (
            <ProductCard key={product.id} product={product}/>
          ))}
        </div>
      </main>
    </>
  );
}
